export type CampaignStatus = "draft" | "active" | "archived";

export type Campaign = {
  id: string;
  organization_id: string;
  slug: string;
  status: CampaignStatus;
  published_at: string | null;
  published_snapshot: Record<string, unknown> | null;
  archived_at: string | null;
  replaces_campaign_id: string | null;
  replaced_by_campaign_id: string | null;
  version: number;
  publication_group_id: string;
  language: string;
  name: string;
  sponsor_type: string | null;
  sponsor_registered_name: string | null;
  sponsor_name: string;
  sponsor_email: string | null;
  sponsor_address: string | null;
  sponsor_establishment: string | null;
  sponsor_registration_number: string | null;
  sponsor_contact: string;
  controlling_entity: string | null;
  controlling_entity_registered_name: string | null;
  controlling_entity_email: string | null;
  controlling_entity_address: string | null;
  controlling_entity_establishment: string | null;
  controlling_entity_registration_number: string | null;
  controlling_entity_contact: string | null;
  payer_name: string | null;
  payer_registered_name: string | null;
  payer_email: string | null;
  payer_address: string | null;
  payer_establishment: string | null;
  payer_registration_number: string | null;
  payer_contact: string | null;
  publisher_name: string | null;
  publisher_contact: string | null;
  period_start: string;
  period_end: string;
  amount_message: number | null;
  amount_campaign: number | null;
  amount_currency: string;
  in_kind_message: number | null;
  in_kind_campaign: number | null;
  amount_basis: string | null;
  amount_includes_vat: boolean | null;
  funds_origin: string | null;
  funds_source_type: string | null;
  funds_source_region: string | null;
  calculation_method: string;
  linked_process: string | null;
  process_type: string | null;
  process_name: string | null;
  process_level: string | null;
  process_date: string | null;
  process_region: string | null;
  official_info_url: string | null;
  eu_database_url: string | null;
  prior_non_compliance: boolean;
  prior_non_compliance_description: string | null;
  targeting_used: boolean;
  targeting_description: string | null;
  targeting_analysis_methods: string | null;
  targeting_audience_groups: string | null;
  targeting_personal_data_categories: string | null;
  targeting_logic: string | null;
  targeting_ai_systems: string | null;
  targeting_period_start: string | null;
  targeting_period_end: string | null;
  targeting_impressions: number | null;
  targeting_clicks: number | null;
  targeting_likes: number | null;
  targeting_comments: number | null;
  targeting_policy_url: string | null;
  targeting_additional_info: string | null;
  delivery_description: string | null;
  consent_withdrawal_url: string | null;
  gdpr_controller_name: string | null;
  gdpr_controller_contact: string | null;
  gdpr_rights_url: string | null;
  gdpr_info_url: string | null;
  complaint_contact: string;
  complaint_url: string | null;
  ad_channels: string[] | null;
  created_at: string;
  updated_at: string;
  organizations?: Organization | null;
  replaces_campaign?: Pick<Campaign, "id" | "name" | "slug" | "version"> | null;
  replaced_by_campaign?: Pick<Campaign, "id" | "name" | "slug" | "version"> | null;
};

export type Organization = {
  id: string;
  name: string;
  org_number: string | null;
  website: string | null;
  legal_form: string | null;
  registered_name: string | null;
  email: string | null;
  address: string | null;
  establishment: string | null;
  created_at: string;
};

export type OrganizationContact = {
  organization_id: string;
  user_id: string;
  email: string;
  role: string | null;
};
