alter table public.campaigns
  add column if not exists sponsor_type text,
  add column if not exists sponsor_registered_name text,
  add column if not exists sponsor_email text,
  add column if not exists sponsor_address text,
  add column if not exists sponsor_establishment text,
  add column if not exists sponsor_registration_number text,
  add column if not exists controlling_entity_email text,
  add column if not exists controlling_entity_address text,
  add column if not exists controlling_entity_establishment text,
  add column if not exists payer_name text,
  add column if not exists payer_registered_name text,
  add column if not exists payer_email text,
  add column if not exists payer_address text,
  add column if not exists payer_establishment text,
  add column if not exists amount_currency text not null default 'SEK',
  add column if not exists in_kind_message numeric(14, 2),
  add column if not exists in_kind_campaign numeric(14, 2),
  add column if not exists amount_basis text,
  add column if not exists amount_includes_vat boolean,
  add column if not exists funds_source_type text,
  add column if not exists funds_source_region text,
  add column if not exists process_type text,
  add column if not exists process_name text,
  add column if not exists process_level text,
  add column if not exists process_date date,
  add column if not exists process_region text,
  add column if not exists official_info_url text,
  add column if not exists eu_database_url text,
  add column if not exists prior_non_compliance boolean not null default false,
  add column if not exists prior_non_compliance_description text,
  add column if not exists targeting_analysis_methods text,
  add column if not exists targeting_audience_groups text,
  add column if not exists targeting_personal_data_categories text,
  add column if not exists targeting_logic text,
  add column if not exists targeting_ai_systems text,
  add column if not exists targeting_period_start date,
  add column if not exists targeting_period_end date,
  add column if not exists targeting_impressions integer,
  add column if not exists targeting_clicks integer,
  add column if not exists targeting_likes integer,
  add column if not exists targeting_comments integer,
  add column if not exists targeting_policy_url text,
  add column if not exists targeting_additional_info text,
  add column if not exists gdpr_controller_name text,
  add column if not exists gdpr_controller_contact text,
  add column if not exists gdpr_rights_url text,
  add column if not exists gdpr_info_url text;
